#!/bin/bash
# Copyright 2022-2024 the Bashy-lib Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

[[ "$(readlink -f "$0")" =~ ^(.*/tests/) ]] && . "${BASH_REMATCH[1]}_test-init.sh" || exit 1

cmd="$(this-cmd-dir)/the-cmd"

call-and-log-as-test 'error-msg' \
    "${cmd}" --func=error-msg

call-and-log-as-test 'info-msg' \
    "${cmd}" --func=info-msg

call-and-log-as-test 'progress-msg' \
    "${cmd}" --func=progress-msg
