#!/bin/bash
# Copyright 2022-2023 the Bashy-lib Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

[[ "$(readlink -f "$0")" =~ ^(.*/tests/) ]] && . "${BASH_REMATCH[1]}_init.sh" || exit 1


#
# Argument parsing
#

define-usage $'
    ${name} -- test command

    This is a test command.
'

# Can't use both `--init` and `--required`.
opt-value --required --var=var1 --init=florp some-value
opt-choice --init=maybe --required --var=var3 yes no
positional-arg --init=x --var=var4 --required some-position

# Can't use `--init` without `--var`.
opt-value --init=x --call=func1 beep
opt-choice --init=x --call=func2 bomp blump
positional-arg --init=x --call=func3 plomp

process-args "$@" || exit "$?"

echo 'Nopers.'
