#!/bin/bash
# Copyright 2022-2024 the Bashy-lib Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

[[ "$(readlink -f "$0")" =~ ^(.*/tests/) ]] && . "${BASH_REMATCH[1]}_init.sh" || exit 1


#
# Argument parsing
#

define-usage $'
    ${name} -- test command

    This is a test command.
'

opt-action --boop --call=func1 act
opt-value --florp --var=var1 some-value
opt-multi --fleep=zonk --call=func1 yes
opt-toggle --default=23 --flomp --var=var2 boop
positional-arg --beep=boop --required --var=var3 some-position
rest-arg --filter='/./' --call=func2 --what-the-muffin the-rest

# Examples of "option-like" but not syntactically correct as options.
opt-value -zonk --var=v x
opt-value ---zonk --var=v x
opt-value --Zomg --var=v x

process-args "$@" || exit "$?"

echo 'Nopers.'
