#!/bin/bash
# Copyright 2022-2025 the Bashy-lib Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

[[ "$(readlink -f "$0")" =~ ^(.*/tests/) ]] && . "${BASH_REMATCH[1]}_test-init.sh" || exit 1

cmd="$(this-cmd-dir)/the-cmd"

call-and-log-as-test 'with -q' \
    "${cmd}" -q

call-and-log-as-test 'with --quiet' \
    "${cmd}" --quiet

call-and-log-as-test 'with --verbose=none' \
    "${cmd}" --verbose=none

call-and-log-as-test 'with --verbose=error' \
    "${cmd}" --verbose=error

call-and-log-as-test 'with --verbose=warn' \
    "${cmd}" --verbose=warn

call-and-log-as-test 'with --verbose=all' \
    "${cmd}" --verbose=all
