#!/bin/bash
# Copyright 2022-2024 the Bashy-lib Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

[[ "$(readlink -f "$0")" =~ ^(.*/tests/) ]] && . "${BASH_REMATCH[1]}_init.sh" || exit 1


#
# Argument parsing
#

define-usage $'
    ${name} -- test command

    This is a test command.
'

positional-arg --required --var=yesArg avec-yes

positional-arg --var=someValue some-value

process-args "$@" || exit "$?"

printf 'avec-yes: %q\n' "${yesArg}"
printf 'some-value: %q\n' "${someValue}"
