#!/bin/bash
#
# Copyright 2022-2023 the Bashy-lib Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

. "$(dirname "$(readlink -f "$0")")/_init.sh" || exit "$?"


#
# Argument parsing
#

define-usage --with-help $'
    ${name} [<opt> ...] [--]

    Runs all the tests.
'

process-args "$@" || usage --short


#
# Main script
#

testsDir="$(this-cmd-dir)"

# Test directories are identified as directories that have a file called `run`
# in them.
jset-array --raw allRunScripts "$(
    lib ls-files --output=array --sort \
        --cd="${testsDir}" --include='^[0-9][-/a-z0-9]+/run' \
    || echo '["error"]'
)" \
|| exit "$?"

if [[ ${allRunScripts[0]} == 'error' ]]; then
    exit 1
fi

errors=0
for run in "${allRunScripts[@]}"; do
    "${testsDir}/run-one" "${run%/run}" \
    || (( errors++ ))
done

if (( errors == 0 )); then
    echo 'All passed. Yay!'
else
    (( errors == 1 )) && noun=error || noun=errors
    echo "${errors} ${noun}. Alas."
    exit 1
fi
