#!/bin/bash
#
# Copyright 2022-2023 the Bashy-lib Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

. "$(dirname "$(readlink -f "$0")")/_init.sh" || exit "$?"


#
# Argument parsing
#

define-usage $'
    ${name} [<opt> ...] [--]

    Runs all the tests.

    ${help}
'

# Want help?
opt-action --call='{ usage; exit }' help/h

process-args "$@" || usage --short


#
# Main script
#

jset-array --raw allRunScripts "$(
    lib ls-files --output=array --sort \
        --cd="$(this-cmd-dir)" --include='^[0-9][-/a-z0-9]+/run' \
    || echo '["error"]'
)" \
|| exit "$?"

if [[ ${allRunScripts[0]} == 'error' ]]; then
    exit 1
fi

errors=0
for run in "${allRunScripts[@]}"; do
    if [[ ! -x "${run}" ]]; then
        echo "Not runnable: ${run}"
        (( errors++ ))
        continue
    fi

    "$(this-cmd-dir)/run-one" "${run%/run}" \
    || (( errors++ ))
done

if (( errors == 0 )); then
    echo 'All passed. Yay!'
else
    echo "${errors} error(s). Alas."
    exit 1
fi
