#!/bin/bash
# Copyright 2022-2023 the Bashy-lib Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

[[ "$(readlink -f "$0")" =~ ^(.*/tests/) ]] && . "${BASH_REMATCH[1]}_test-init.sh" || exit 1

cmd="$(this-cmd-dir)/the-cmd"

call-and-log-as-test 'no args or options passed' \
    "${cmd}"

call-and-log-as-test 'passed one positional arg, matching filter' \
    "${cmd}" green

call-and-log-as-test 'passed one positional arg, not matching filter' \
    "${cmd}" 'fleep?'

call-and-log-as-test 'passed two positional args, both matching' \
    "${cmd}" calico kitten

call-and-log-as-test 'passed two positional args, first matching and second not' \
    "${cmd}" spotted wrench

call-and-log-as-test 'passed two positional args, first non-matching and second matching' \
    "${cmd}" 88 toaster

call-and-log-as-test 'passed two positional args, neither matching' \
    "${cmd}" '@' crumpet
