#!/bin/bash
# Copyright 2022-2023 the Bashy-lib Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

[[ "$(readlink -f "$0")" =~ ^(.*/tests/) ]] && . "${BASH_REMATCH[1]}_init.sh" || exit 1


#
# Argument parsing
#

define-usage $'
    ${name} -- test command

    This is a test command.
'

positional-arg --var=theColor --default=transparent --filter='/^[a-z]+$/' color
positional-arg --var=theItem --default=nothing --enum='kitten puppy toaster' item

process-args "$@" || exit "$?"

printf 'color: %q\n' "${theColor}"
printf 'item: %q\n' "${theItem}"
