#!/bin/bash
# Copyright 2022-2023 the Bashy-lib Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

[[ "$(readlink -f "$0")" =~ ^(.*/tests/) ]] && . "${BASH_REMATCH[1]}_init.sh" || exit 1


#
# Argument parsing
#

define-usage $'
    ${name} -- test command

    This is a test command.
'

# This will work.
opt-action --var=var1 the-one

opt-action --var=var1 the-one
opt-multi --var=var1 the-one
opt-toggle --var=var1 the-one
opt-value --var=var1 the-one
positional-arg --var=var1 the-one
rest-arg --var=var1 the-one

# This will work.
rest-arg --var=var2 a-rest

rest-arg --var=var3 different-name


process-args "$@" || exit "$?"

echo 'Nopers.'
