#!/bin/bash
# Copyright 2022-2023 the Bashy-lib Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

[[ "$(readlink -f "$0")" =~ ^(.*/tests/) ]] && . "${BASH_REMATCH[1]}_test-init.sh" || exit 1

cmd="$(this-cmd-dir)/the-cmd"

call-and-log-as-test 'no args or options passed' \
    "${cmd}"

call-and-log-as-test 'passed `--`' \
    "${cmd}" --

call-and-log-as-test 'passed positional arg' \
    "${cmd}" i-am-arguing

call-and-log-as-test 'passed multi-value option, no values' \
    "${cmd}" --items[]=

call-and-log-as-test 'passed multi-value option, one value' \
    "${cmd}" --items[]='one'

call-and-log-as-test 'passed multi-value option, one value, using single-value syntax' \
    "${cmd}" --items='one'

call-and-log-as-test 'passed multi-value option, one empty value, using single-value syntax' \
    "${cmd}" --items=''

call-and-log-as-test 'passed multi-value option, one single-quoted value with a space' \
    "${cmd}" --items[]="'yes yes'"

call-and-log-as-test 'passed multi-value option, one double-quoted value with a space' \
    "${cmd}" --items[]='"two two"'

call-and-log-as-test 'passed multi-value option, one dollar-quoted value with a space' \
    "${cmd}" --items[]=$'$\'yes sirree!\''

call-and-log-as-test 'passed multi-value option, two values' \
    "${cmd}" --items[]='one two'

call-and-log-as-test 'passed multi-value option, four values, omnibus' \
    "${cmd}" --items[]=$'one "two" \'three four\' $\'five & six\''

call-and-log-as-test 'passed multi-value option, with invalid multi-value syntax #1' \
    "${cmd}" --items[]=$'one "two'

call-and-log-as-test 'passed multi-value option, with invalid multi-value syntax #2' \
    "${cmd}" --items[]=$'a ; b'

call-and-log-as-test 'passed multi-value option, with invalid multi-value syntax #3' \
    "${cmd}" --items[]=$'$c'

call-and-log-as-test 'passed multi-value option, with invalid multi-value syntax #4' \
    "${cmd}" --items[]=$'d|e f&g'

call-and-log-as-test 'passed multi-value option, with invalid multi-value syntax #5' \
    "${cmd}" --items[]=$'x\\ y'

call-and-log-as-test 'passed multi-value option, with invalid multi-value syntax #6' \
    "${cmd}" --items[]=$'x \'y'

call-and-log-as-test 'passed multi-value option, with invalid multi-value syntax #7' \
    "${cmd}" --items[]=$'x $\'oopsie'

call-and-log-as-test 'passed multi-value option, with invalid multi-value syntax #8' \
    "${cmd}" --items[]=$'"boop'

call-and-log-as-test 'passed multi-value option, with invalid multi-value syntax #9' \
    "${cmd}" --items[]=$'\'x\'\'y\''

call-and-log-as-test 'passed multi-value option, showing that double-quoted strings are literal' \
    "${cmd}" --items[]='"$(echo hi)" "\n" "${florp}"'
