#!/bin/bash
# Copyright 2022-2024 the Bashy-lib Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

[[ "$(readlink -f "$0")" =~ ^(.*/tests/) ]] && . "${BASH_REMATCH[1]}_init.sh" || exit 1


#
# Argument parsing
#

define-usage $'
    ${name} -- test command

    This is a test command.
'

opt-value --var=value --enum[]='x' just-x
opt-value --var=value --enum[]='x y' xy
opt-value --var=value --enum[]=' x y' space-prefix-xy
opt-value --var=value --enum[]='x y ' space-suffix-xy
opt-value --var=value --enum[]='   lots   of      spaces     ' lots-of-spaces
opt-value --var=value \
    --enum[]='abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ 0123456789 - : _ .' \
    all-symbol-chars
opt-value --var=value --enum[]=$'\'a b\' $\'c d\' "efg"' quoted-forms

process-args "$@" || exit "$?"

printf 'value: %q\n' "${value}"
