#!/bin/bash
# Copyright 2022-2025 the Bashy-lib Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

[[ "$(readlink -f "$0")" =~ ^(.*/tests/) ]] && . "${BASH_REMATCH[1]}_test-init.sh" || exit 1

cmd="$(this-cmd-dir)/the-cmd"

call-and-log-as-test 'not set' \
    "${cmd}" --not-set

call-and-log-as-test 'set absolute path' \
    "${cmd}" --absolute

call-and-log-as-test 'set relative path' \
    "${cmd}" --relative
