#!/bin/bash
# Copyright 2022-2023 the Bashy-lib Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

[[ "$(readlink -f "$0")" =~ ^(.*/tests/) ]] && . "${BASH_REMATCH[1]}_init.sh" || exit 1


#
# Argument parsing
#

define-usage $'
    ${name} -- test command

    This is a test command.
'

opt-action --required --var=var1 some-action
opt-toggle --required --var=var1 some-toggle
rest-arg --required --var=var1 some-rest


process-args "$@" || exit "$?"

echo 'Nopers.'
