#!/bin/bash
# Copyright 2022-2023 the Bashy-lib Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

[[ "$(readlink -f "$0")" =~ ^(.*/tests/) ]] && . "${BASH_REMATCH[1]}_init.sh" || exit 1


#
# Argument parsing
#

define-usage $'
    ${name} -- test command

    This is a test command.
'

# Empty.
opt-value --var=value --enum[]='' x
opt-value --var=value --enum[]=' ' x
opt-value --var=value --enum[]='  ' x
opt-value --var=value --enum[]='   ' x

# Disallowed value characters, individually.
opt-value --var=value --enum[]='`' x
opt-value --var=value --enum[]='$' x
opt-value --var=value --enum[]=',' x
opt-value --var=value --enum[]=';' x
opt-value --var=value --enum[]='|' x
opt-value --var=value --enum[]='@' x
opt-value --var=value --enum[]='#' x

# Disallowed value characters, embedded.
opt-value --var=value --enum[]='@hello' x
opt-value --var=value --enum[]='hello@' x
opt-value --var=value --enum[]='hello@there' x
opt-value --var=value --enum[]='x y,z' x
opt-value --var=value --enum[]='x ab| y' x
opt-value --var=value --enum[]='x #ab y' x

process-args "$@" || exit "$?"

echo 'Nopers.'
