#!/bin/bash
# Copyright 2022-2024 the Bashy-lib Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

[[ "$(readlink -f "$0")" =~ ^(.*/tests/) ]] && . "${BASH_REMATCH[1]}_test-init.sh" || exit 1

cmd="$(this-cmd-dir)/the-cmd"

call-and-log-as-test 'no args or options passed' \
    "${cmd}"

call-and-log-as-test 'passed `--`' \
    "${cmd}" --

call-and-log-as-test 'passed positional arg' \
    "${cmd}" i-am-arguing

call-and-log-as-test 'passed value option with no default, empty value' \
    "${cmd}" --item=

call-and-log-as-test 'passed value option with no default, non-empty value' \
    "${cmd}" --item=kitten

call-and-log-as-test 'passed value option with default, empty value' \
    "${cmd}" --color=

call-and-log-as-test 'passed value option with default, non-empty value' \
    "${cmd}" --color=blue

call-and-log-as-test 'passed two value options' \
    "${cmd}" --item=puppy --color=purple

call-and-log-as-test 'passed two values to (single) value option' \
    "${cmd}" --item[]='florp fleep'
