#!/bin/bash
# Copyright 2022-2025 the Bashy-lib Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

[[ "$(readlink -f "$0")" =~ ^(.*/tests/) ]] && . "${BASH_REMATCH[1]}_init.sh" || exit 1


#
# Argument parsing
#

define-usage $'
    ${name} -- test command

    This is a test command.
'

opt-value --var=theItem item
opt-value --var=theColor --default=red color

process-args "$@" || exit "$?"

printf 'item: %q\n' "${theItem}"
printf 'color: %q\n' "${theColor}"
