#!/bin/bash
# Copyright 2022-2025 the Bashy-lib Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

[[ "$(readlink -f "$0")" =~ ^(.*/tests/) ]] && . "${BASH_REMATCH[1]}_test-init.sh" || exit 1

function report {
    local nlOpt=()
    if [[ $1 == --nl-terminated ]]; then
        nlOpt="$1"
        shift
    fi

    local lines="$1"

    set-array-from-lines "${nlOpt[@]}" theArray "${lines}" || return "$?"

    printf 'Length: %s\n' "${#theArray[@]}"

    if (( ${#theArray[@]} != 0 )); then
        printf '\n'
        local n
        for n in "${!theArray[@]}"; do
            printf '%s: %q\n' "${n}" "${theArray[n]}"
        done
    fi
}

function do-count {
    local length="$1"

    local theArray=()
    local lines=''

    local n
    for (( n = 0; n < length; n++ )); do
        lines+="$(printf 'line-%s' "${n}")"$'\n'
    done

    report "${lines}"
}

function do-string {
    local string="$1"

    report "${string}"
}

function do-string-nl {
    local string="$1"

    report 2>&1 --nl-terminated "${string}"
}

call-and-log-as-test 'no elements' \
    do-count 0

call-and-log-as-test 'one element' \
    do-count 1

call-and-log-as-test 'two elements' \
    do-count 2

call-and-log-as-test '25 elements' \
    do-count 25

call-and-log-as-test 'just newline' \
    do-string $'\n'

call-and-log-as-test 'just two newlines' \
    do-string $'\n\n'

call-and-log-as-test 'one line with newline at start and end' \
    do-string $'\nzorch\n'

call-and-log-as-test 'five lines with two newlines at start and end' \
    do-string $'\n\nalpha\nbeta\ngamma\ndelta\nepsilon\n\n'

call-and-log-as-test 'two lines with four newlines in the middle' \
    do-string $'start\n\n\n\nend'

call-and-log-as-test 'nl-terminated: empty string' \
    do-string-nl $''

call-and-log-as-test 'nl-terminated: just newline' \
    do-string-nl $'\n'

call-and-log-as-test 'nl-terminated: just two newlines' \
    do-string-nl $'\n\n'

call-and-log-as-test 'nl-terminated: one line with newline at start and end' \
    do-string-nl $'\nzorch\n'

call-and-log-as-test 'nl-terminated: five lines with two newlines at start and end' \
    do-string-nl $'\n\nalpha\nbeta\ngamma\ndelta\nepsilon\n\n'

call-and-log-as-test 'nl-terminated: two lines with four newlines in the middle and one at end' \
    do-string-nl $'start\n\n\n\nend\n'

call-and-log-as-test 'nl-terminated: one non-nl-terminated line' \
    do-string-nl $'beep boop'

call-and-log-as-test 'nl-terminated: two lines, non-nl-terminated at the end' \
    do-string-nl $'beep\nboop'
