#!/bin/bash
# Copyright 2022-2025 the Bashy-lib Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

[[ "$(readlink -f "$0")" =~ ^(.*/tests/) ]] && . "${BASH_REMATCH[1]}_test-init.sh" || exit 1

cmd="$(this-cmd-dir)/the-cmd"

call-and-log-as-test 'passed multi-value option, no values' \
    "${cmd}" --items[]=

call-and-log-as-test 'passed multi-value option, one matching value' \
    "${cmd}" --items[]='123x789z'

call-and-log-as-test 'passed multi-value option, one non-matching value' \
    "${cmd}" --items[]='123789'

call-and-log-as-test 'passed multi-value option, two matching values' \
    "${cmd}" --items[]='xz blorpx-z'

call-and-log-as-test 'passed multi-value option, first matching, second not' \
    "${cmd}" --items[]='xz blorp'

call-and-log-as-test 'passed multi-value option, first non-matching, second matching' \
    "${cmd}" --items[]='beep bxx-boopz'
