#!/bin/bash
# Copyright 2022-2023 the Bashy-lib Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

[[ "$(readlink -f "$0")" =~ ^(.*/tests/) ]] && . "${BASH_REMATCH[1]}_init.sh" || exit 1


#
# Argument parsing
#

define-usage $'
    ${name} -- test command

    This is a test command.
'

opt-value --var=value --filter='{:}' nop
opt-value --var=value --filter='{replace-value "<$1>"}' wrap
opt-value --var=value --filter='{
        x="$1"
        replace-value "${x}!!"
    }' multiline
opt-value --var=value --filter='{
        if [[ $1 == a ]]; then
            error-msg "Not a!"
            return 1
        fi
    }' fail-on-a

florp='do not like'
origFlorp="${florp}"
opt-value --var=value --filter='{
        florp="$1"
    }' set-florp

process-args "$@" || exit "$?"

printf 'value: %q\n' "${value}"
if [[ ${florp} != ${origFlorp} ]]; then
    echo "florp: $(vals "${florp}")"
fi
