#!/bin/bash
# Copyright 2022-2023 the Bashy-lib Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

[[ "$(readlink -f "$0")" =~ ^(.*/tests/) ]] && . "${BASH_REMATCH[1]}_init.sh" || exit 1


#
# Argument parsing
#

define-usage $'
    ${name} -- test command

    This is a test command.
'

opt-alias --default=zoop some-alias --x
opt-multi --var=var1 --default=x some-multi
rest-arg --var=var1 --default=y some-rest

process-args "$@" || exit "$?"

echo 'Nopers.'
