#!/bin/bash
# Copyright 2022-2023 the Bashy-lib Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

[[ "$(readlink -f "$0")" =~ ^(.*/tests/) ]] && . "${BASH_REMATCH[1]}_test-init.sh" || exit 1

cmd="$(this-cmd-dir)/the-cmd"

call-and-log-as-test 'nop filter' \
    "${cmd}" --nop=xyz

call-and-log-as-test 'simple wrapping filter' \
    "${cmd}" --wrap=pdq

call-and-log-as-test 'multiline simple filter' \
    "${cmd}" --multiline=yes

call-and-log-as-test 'multiline filter that rejects `a`, given not-`a`' \
    "${cmd}" --fail-on-a=not-a

call-and-log-as-test 'multiline filter that rejects `a`, given `a`' \
    "${cmd}" --fail-on-a=a

# This demonstrates that the filter doesn't run in a subshell.
call-and-log-as-test 'filter which modifies a global' \
    "${cmd}" --set-florp=like
