#!/bin/bash
# Copyright 2022-2024 the Bashy-lib Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

[[ "$(readlink -f "$0")" =~ ^(.*/tests/) ]] && . "${BASH_REMATCH[1]}_init.sh" || exit 1


#
# Argument parsing
#

define-usage $'
    ${name} -- test command

    This is a test command.
'

rest-arg --var=stuff stuff

process-args "$@" || exit "$?"

echo "Count: ${#stuff[@]}"

if (( ${#stuff[@]} != 0 )); then
    for n in "${!stuff[@]}"; do
        printf '  %s: %q\n' "${n}" "${stuff[n]}"
    done
fi
