#!/bin/bash
# Copyright 2022-2024 the Bashy-lib Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

[[ "$(readlink -f "$0")" =~ ^(.*/tests/) ]] && . "${BASH_REMATCH[1]}_test-init.sh" || exit 1

cmd="$(this-cmd-dir)/the-cmd"

call-and-log-as-test 'no args or options passed' \
    "${cmd}"

call-and-log-as-test 'passed `--`' \
    "${cmd}" --

call-and-log-as-test 'passed positional arg' \
    "${cmd}" i-am-arguing

call-and-log-as-test 'passed multi-value option, no values' \
    "${cmd}" --items[]=

call-and-log-as-test 'passed multi-value option, one value' \
    "${cmd}" --items[]='one'

call-and-log-as-test 'passed multi-value option, one value, using single-value syntax' \
    "${cmd}" --items='one'

call-and-log-as-test 'passed multi-value option, one empty value, using single-value syntax' \
    "${cmd}" --items=''

call-and-log-as-test 'passed multi-value option, one single-quoted value with a space' \
    "${cmd}" --items[]="'yes yes'"

call-and-log-as-test 'passed multi-value option, one double-quoted value with a space' \
    "${cmd}" --items[]='"two two"'

call-and-log-as-test 'passed multi-value option, one dollar-quoted value with a space' \
    "${cmd}" --items[]=$'$\'yes sirree!\''

call-and-log-as-test 'passed multi-value option, two values' \
    "${cmd}" --items[]='one two'

call-and-log-as-test 'passed multi-value option, four values, omnibus' \
    "${cmd}" --items[]=$'one "two" \'three four\' $\'five & six\''
