#!/bin/bash
# Copyright 2022-2023 the Bashy-lib Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

[[ "$(readlink -f "$0")" =~ ^(.*/tests/) ]] && . "${BASH_REMATCH[1]}_init.sh" || exit 1


#
# The test.
#

define-usage $'
    ${name} -- This is the short
    help for the command.

    This is the longer help.

    ${name} another-option-variant

    And more help about that.
'

what="$1"

case "${what}" in
    long)
        usage
        echo 1>&2 '(no exit expected; should see this)'
        ;;
    short)
        echo 1>&2 'This is not actually an error! (But we can pretend.)'
        usage --short
        echo 1>&2 '(no exit expected; should see this)'
        ;;
    *)
        echo 1>&2 'This is an error!'
        (exit "${what}") || usage --short
        echo 1>&2 '(exit expected; should not see this)'
        ;;
esac
