#!/bin/bash
# Copyright 2022-2023 the Bashy-lib Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

[[ "$(readlink -f "$0")" =~ ^(.*/tests/) ]] && . "${BASH_REMATCH[1]}_test-init.sh" || exit 1

cmd="$(this-cmd-dir)/the-cmd"

call-and-log-as-test 'no args or options passed' \
    "${cmd}"

call-and-log-as-test 'passed `--`' \
    "${cmd}" --

call-and-log-as-test 'passed positional arg' \
    "${cmd}" i-am-arguing

call-and-log-as-test 'passed long choice with no defined value or short form' \
    "${cmd}" --zero

call-and-log-as-test 'passed long choice with short form but no defined value' \
    "${cmd}" --one

call-and-log-as-test 'passed short choice with no defined value' \
    "${cmd}" -o

call-and-log-as-test 'passed long choice with short form and defined value' \
    "${cmd}" --two

call-and-log-as-test 'passed short choice with defined value' \
    "${cmd}" -t

call-and-log-as-test 'passed long choice with defined value but no short form' \
    "${cmd}" --three

call-and-log-as-test 'passed two choices from the same set' \
    "${cmd}" --one --two

call-and-log-as-test 'passed three choices from the same set' \
    "${cmd}" --one --two --three

call-and-log-as-test 'passed value to choice' \
    "${cmd}" --one=florp

call-and-log-as-test 'passed two values to choice' \
    "${cmd}" --one[]='florp fleep'
