#!/bin/bash
# Copyright 2022-2024 the Bashy-lib Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

[[ "$(readlink -f "$0")" =~ ^(.*/tests/) ]] && . "${BASH_REMATCH[1]}_init.sh" || exit 1


#
# The test.
#

define-usage $'
    ${name} -- This is the short
    help for the command.

    This is the longer help.

    ${name} another-option-variant

    And more help about that.
'

what="$1"

case "${what}" in
    long)
        usage
        ;;
    short)
        usage --short
        ;;
    *)
        # Old behavior was that `usage` would magically `exit` if `$?` was
        # non-zero upon entry. This test now verifies that it no longer does
        # that.
        (exit "${what}") || usage --short
        ;;
esac

echo 'Done.'
