#!/bin/bash
# Copyright 2022-2024 the Bashy-lib Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

[[ "$(readlink -f "$0")" =~ ^(.*/tests/) ]] && . "${BASH_REMATCH[1]}_test-init.sh" || exit 1

cmd="$(this-cmd-dir)/the-cmd"

call-and-log-as-test 'no args or options passed' \
    "${cmd}"

call-and-log-as-test 'passed `--`' \
    "${cmd}" --

call-and-log-as-test 'passed positional arg' \
    "${cmd}" i-am-arguing

call-and-log-as-test 'passed long action with no default or defined value' \
    "${cmd}" --run

call-and-log-as-test 'passed long action with default and defined value' \
    "${cmd}" --perhaps

call-and-log-as-test 'passed long action with defined value and defined short form' \
    "${cmd}" --fly

call-and-log-as-test 'passed short action with defined value' \
    "${cmd}" -f

call-and-log-as-test 'passed three long actions' \
    "${cmd}" --run --perhaps --fly

call-and-log-as-test 'passed value to action' \
    "${cmd}" --run=florp

call-and-log-as-test 'passed two values to action' \
    "${cmd}" --run[]='florp fleep'
