#!/bin/bash
# Copyright 2022-2023 the Bashy-lib Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

. "$(dirname "$(readlink -f "$0")")/../../_init.sh" || exit "$?"

# This space intentionally left blank. The point is to verify that the library
# can initialize itself without error.
